/**
 * daily-report — end-of-day report
 * ================================
 * Collects every pi session of a given day and produces:
 *   1. a fast table (panel): time, duration, project, prompt count, tokens, first message
 *   2. an AI summary: done vs not finished / to continue
 *
 * Commands:
 *   /report                  table + AI summary for today
 *   /report fast              table only for today (no AI call, instant)
 *   /report yesterday         table + summary for yesterday
 *   /report 2026-10-04        table + summary for a specific date (YYYY-MM-DD)
 *   /report 2026-10-04 fast   table only for a specific date
 *   /report export [file]     save today's markdown report (default: ./report-YYYY-MM-DD.md)
 *   /daily                    alias of /report
 *
 * How it works:
 * - reads ~/.pi/agent/sessions/<project>/*.jsonl
 * - includes sessions with activity (file mtime) on the target day,
 *   even if started on a previous day (marked with *)
 * - the summary is generated by the current model in a single call, no tools
 * - outside the TUI (e.g. pi -p) everything goes to stdout: usable from scripts
 */

import {
	getAgentDir,
	type ExtensionAPI,
	type ExtensionCommandContext,
	type Theme,
} from "@earendil-works/pi-coding-agent";
import type { Message } from "@earendil-works/pi-ai";
import type { Component } from "@earendil-works/pi-tui";
import { Box, Text } from "@earendil-works/pi-tui";
import fs from "node:fs";
import path from "node:path";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Char budget for the single-session digest sent to the model. */
const SESSION_DIGEST_CHARS = 2_200;
/** Total digest budget for the AI summary. */
const TOTAL_DIGEST_CHARS = 20_000;
/** Timeout for the summary call. */
const SUMMARY_TIMEOUT_MS = 120_000;
/** First message shown in full only in export; truncated in the table. */
const FIRST_MSG_CHARS = 400;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SessionDigest {
	id: string;
	cwd: string;
	projectShort: string;
	startedAt: string; // ISO
	endedAt: string; // ISO
	resumed: boolean; // started on a previous day
	userPrompts: string[];
	lastAssistant: string;
	filesTouched: string[];
	commands: string[];
	tokens: number;
	errors: number;
}

interface DayReport {
	date: string; // YYYY-MM-DD (local)
	generatedAt: string; // ISO
	sessions: SessionDigest[];
	totalPrompts: number;
	totalTokens: number;
	totalFiles: number;
	rangeStart: string;
	rangeEnd: string;
}

// ---------------------------------------------------------------------------
// Generic helpers
// ---------------------------------------------------------------------------

function localDateKey(input: string | Date): string {
	const d = typeof input === "string" ? new Date(input) : input;
	if (Number.isNaN(d.getTime())) return "";
	const y = d.getFullYear();
	const m = String(d.getMonth() + 1).padStart(2, "0");
	const day = String(d.getDate()).padStart(2, "0");
	return `${y}-${m}-${day}`;
}

function localTime(input: string | Date): string {
	const d = typeof input === "string" ? new Date(input) : input;
	if (Number.isNaN(d.getTime())) return "--:--";
	return `${String(d.getHours()).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}`;
}

function shortDay(iso: string): string {
	const d = new Date(iso);
	if (Number.isNaN(d.getTime())) return "";
	return `${d.getDate()}/${d.getMonth() + 1}`;
}

/** Sort key: resumed sessions are placed at their activity of the day (end). */
function sortKey(s: SessionDigest): string {
	return s.resumed ? s.endedAt : s.startedAt;
}

/** Range for the TUI table (compact). */
function fmtRangeTable(s: SessionDigest): string {
	if (s.resumed) return `${shortDay(s.startedAt)}→${localTime(s.endedAt)}*`;
	return `${localTime(s.startedAt)}–${localTime(s.endedAt)}`;
}

/** Wall-clock start-to-end duration (non-resumed sessions only). */
function fmtDur(startIso: string, endIso: string): string {
	const ms = new Date(endIso).getTime() - new Date(startIso).getTime();
	if (!Number.isFinite(ms) || ms < 0) return "";
	const mins = Math.round(ms / 60000);
	if (mins < 1) return "<1m";
	if (mins < 60) return mins + "m";
	const h = Math.floor(mins / 60);
	const m = mins % 60;
	if (h < 24) return m === 0 ? h + "h" : h + "h " + m + "m";
	return Math.floor(h / 24) + "d " + (h % 24) + "h";
}

/** Range for markdown/digest (explicit). */
function fmtRangeMd(s: SessionDigest): string {
	if (s.resumed) return `${shortDay(s.startedAt)} ${localTime(s.startedAt)} → ${localTime(s.endedAt)} *`;
	return `${localTime(s.startedAt)}–${localTime(s.endedAt)}`;
}

/** Range + duration for non-resumed sessions. */
function fmtRangeDur(s: SessionDigest): string {
	return `${fmtRangeMd(s)} (${fmtDur(s.startedAt, s.endedAt)})`;
}

function addDays(dateKey: string, delta: number): string {
	const [y, m, d] = dateKey.split("-").map(Number);
	const dt = new Date(y, m - 1, d + delta, 12, 0, 0, 0);
	return localDateKey(dt);
}

function trimZeros(s: string): string {
	return s.replace(/\.?0+$/, "");
}

function fmtTokens(n: number): string {
	const abs = Math.abs(n);
	if (abs >= 1_000_000) return trimZeros((n / 1_000_000).toFixed(1)) + "M";
	if (abs >= 1_000) return trimZeros((n / 1_000).toFixed(1)) + "K";
	return String(Math.round(n));
}

function truncate(s: string, max: number): string {
	const chars = Array.from(s);
	if (chars.length <= max) return s;
	return chars.slice(0, Math.max(0, max - 1)).join("") + "…";
}

function padRight(s: string, width: number): string {
	const t = truncate(s, width);
	return t + " ".repeat(Math.max(0, width - Array.from(t).length));
}

function padLeft(s: string, width: number): string {
	const t = truncate(s, width);
	return " ".repeat(Math.max(0, width - Array.from(t).length)) + t;
}

function oneLine(s: string): string {
	return s.replace(/\s+/g, " ").trim();
}

function shortPath(p: string, home: string): string {
	if (p.startsWith(home)) return "~" + p.slice(home.length);
	return p;
}

/** "…/Progetti/xxx" -> "xxx", "~" stays "~". */
function projectShort(cwd: string, home: string): string {
	if (!cwd) return "?";
	if (cwd === home) return "~";
	const parts = cwd.split("/").filter(Boolean);
	if (parts.length === 0) return cwd;
	// Keep the last 2 segments when the last one is generic (src, app, be, fe...)
	const last = parts[parts.length - 1];
	const generic = new Set(["src", "app", "be", "fe", "backend", "frontend", "packages"]);
	if (generic.has(last.toLowerCase()) && parts.length >= 2) {
		return `${parts[parts.length - 2]}/${last}`;
	}
	return last;
}

function englishDate(dateKey: string): string {
	const [y, m, d] = dateKey.split("-").map(Number);
	const dt = new Date(y, m - 1, d, 12, 0, 0, 0);
	try {
		return dt.toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" });
	} catch {
		return dateKey;
	}
}

// ---------------------------------------------------------------------------
// Session reading
// ---------------------------------------------------------------------------

function sessionsRoot(): string {
	return path.join(getAgentDir(), "sessions");
}

/** Extracts only the text parts from a generic message content. */
function contentText(content: unknown): string {
	if (typeof content === "string") return content;
	if (!Array.isArray(content)) return "";
	const parts: string[] = [];
	for (const part of content as Array<Record<string, unknown>>) {
		if (part && part.type === "text" && typeof part.text === "string") parts.push(part.text);
	}
	return parts.join("\n");
}

function parseSessionFile(file: string, targetDate: string, home: string): SessionDigest | null {
	let stat: fs.Stats;
	try {
		stat = fs.statSync(file);
	} catch {
		return null;
	}
	// Day filter: activity (file mtime) on the target day.
	if (localDateKey(stat.mtime) !== targetDate) return null;

	let content: string;
	try {
		content = fs.readFileSync(file, "utf8");
	} catch {
		return null;
	}

	let id = path.basename(file).replace(/\.jsonl$/, "");
	let cwd = "";
	let startedAt = "";
	let endedAt = "";
	const userPrompts: string[] = [];
	let lastAssistant = "";
	const filesTouched: string[] = [];
	const seenFiles = new Set<string>();
	const commands: string[] = [];
	let tokens = 0;
	let errors = 0;

	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed) continue;
		let e: Record<string, any>;
		try {
			e = JSON.parse(trimmed) as Record<string, any>;
		} catch {
			continue;
		}

		const ts = typeof e.timestamp === "string" ? e.timestamp : "";
		if (ts && (!endedAt || ts > endedAt)) endedAt = ts;

		// Tokens: any entry with usage.totalTokens (assistant, usage, compaction, ...)
		const usage = e.usage ?? e.message?.usage;
		const t = usage?.totalTokens;
		if (typeof t === "number" && Number.isFinite(t)) tokens += t;

		if (e.type === "session") {
			if (typeof e.id === "string") id = e.id;
			if (typeof e.timestamp === "string") startedAt = e.timestamp;
			if (typeof e.cwd === "string") cwd = e.cwd;
			continue;
		}

		if (e.type !== "message" || !e.message || typeof e.message !== "object") continue;
		const role = e.message.role;
		if (role === "user") {
			const text = oneLine(contentText(e.message.content));
			if (text) userPrompts.push(text);
		} else if (role === "assistant") {
			const c = e.message.content;
			if (Array.isArray(c)) {
				const texts: string[] = [];
				for (const part of c) {
					if (!part || typeof part !== "object") continue;
					if (part.type === "text" && typeof part.text === "string" && part.text.trim()) {
						texts.push(part.text);
					} else if (part.type === "toolCall") {
						const name = part.name;
						const args = part.arguments ?? {};
						if ((name === "edit" || name === "write") && typeof args.path === "string") {
							if (!seenFiles.has(args.path)) {
								seenFiles.add(args.path);
								filesTouched.push(args.path);
							}
						} else if (name === "bash" && typeof args.command === "string") {
							const cmd = oneLine(args.command);
							// Skip read-only/search commands, not informative.
							if (commands.length < 4 && cmd && !/^(rg|ls|find|cat|head|tail|pwd|echo)\b/.test(cmd)) {
								commands.push(truncate(cmd, 100));
							}
						}
					}
				}
				if (texts.length > 0) lastAssistant = oneLine(texts.join("\n"));
			}
		} else if (role === "toolResult") {
			if (e.message.isError) errors += 1;
		}
	}

	if (!startedAt) startedAt = new Date(stat.mtimeMs).toISOString();
	if (!endedAt) endedAt = startedAt;
	const startDay = localDateKey(startedAt);

	return {
		id,
		cwd,
		projectShort: projectShort(cwd, home),
		startedAt,
		endedAt,
		resumed: !!startDay && startDay !== targetDate,
		userPrompts,
		lastAssistant,
		filesTouched,
		commands,
		tokens,
		errors,
	};
}

function collectDay(targetDate: string): DayReport {
	const home = process.env.HOME || "";
	const sessions: SessionDigest[] = [];
	let root: string[];
	try {
		root = fs.readdirSync(sessionsRoot(), { encoding: "utf8" });
	} catch {
		root = [];
	}
	for (const dir of root) {
		const full = path.join(sessionsRoot(), dir);
		let files: string[];
		try {
			if (!fs.statSync(full).isDirectory()) continue;
			files = fs.readdirSync(full, { encoding: "utf8" }).filter((f) => f.endsWith(".jsonl"));
		} catch {
			continue;
		}
		for (const f of files) {
			try {
				const digest = parseSessionFile(path.join(full, f), targetDate, home);
				if (digest) sessions.push(digest);
			} catch {
				// One unreadable session must not break the report.
			}
		}
	}
	sessions.sort((a, b) => (sortKey(a) < sortKey(b) ? -1 : sortKey(a) > sortKey(b) ? 1 : 0));

	const files = new Set<string>();
	let totalPrompts = 0;
	let totalTokens = 0;
	for (const s of sessions) {
		totalPrompts += s.userPrompts.length;
		totalTokens += s.tokens;
		for (const f of s.filesTouched) files.add(f);
	}

	return {
		date: targetDate,
		generatedAt: new Date().toISOString(),
		sessions,
		totalPrompts,
		totalTokens,
		totalFiles: files.size,
		rangeStart: sessions.length > 0 ? sessions.reduce((m, s) => (sortKey(s) < m ? sortKey(s) : m), sortKey(sessions[0])) : "",
		rangeEnd: sessions.length > 0 ? sessions.reduce((m, s) => (s.endedAt > m ? s.endedAt : m), sessions[0].endedAt) : "",
	};
}

// ---------------------------------------------------------------------------
// Digest for the model
// ---------------------------------------------------------------------------

function sessionDigestText(s: SessionDigest, home: string): string {
	const lines: string[] = [];
	const time = s.resumed ? fmtRangeMd(s) : fmtRangeDur(s);
	lines.push(`### [${time}] ${s.projectShort}${s.resumed ? " (resumed from a previous day)" : ""} — ${s.userPrompts.length} prompt${s.userPrompts.length === 1 ? "" : "s"}, ~${fmtTokens(s.tokens)} tokens${s.errors > 0 ? `, ${s.errors} tool errors` : ""}`);
	const prompts = s.userPrompts.slice(0, 6);
	prompts.forEach((p, i) => {
		lines.push(`- prompt ${i + 1}: ${truncate(p, i === 0 ? FIRST_MSG_CHARS : 220)}`);
	});
	if (s.userPrompts.length > prompts.length) {
		lines.push(`- … +${s.userPrompts.length - prompts.length} more prompts`);
	}
	if (s.filesTouched.length > 0) {
		const files = s.filesTouched.slice(0, 10).map((f) => shortPath(f, home));
		lines.push(`- files changed (${s.filesTouched.length}): ${files.join(", ")}${s.filesTouched.length > 10 ? " …" : ""}`);
	}
	if (s.commands.length > 0) {
		lines.push(`- commands: ${s.commands.join(" | ")}`);
	}
	if (s.lastAssistant) {
		lines.push(`- last assistant message: ${truncate(s.lastAssistant, 700)}`);
	}
	return truncate(lines.join("\n"), SESSION_DIGEST_CHARS);
}

function buildDigest(report: DayReport): string {
	const home = process.env.HOME || "";
	const parts = report.sessions.map((s) => sessionDigestText(s, home));
	let digest = parts.join("\n\n");
	if (digest.length > TOTAL_DIGEST_CHARS) {
		digest = digest.slice(0, TOTAL_DIGEST_CHARS) + "\n… [digest truncated]";
	}
	return digest;
}

// ---------------------------------------------------------------------------
// Render: table panel (TUI)
// ---------------------------------------------------------------------------

function renderTablePanel(report: DayReport, theme: Theme): Component {
	const fg = (color: "accent" | "success" | "warning" | "error" | "muted" | "dim" | "text", text: string) =>
		theme.fg(color, text);

	const lines: string[] = [];
	lines.push(
		fg("accent", `Day report — ${englishDate(report.date)}`) +
			fg("muted", `  (${report.sessions.length} sessions · ${report.totalPrompts} prompts · ${fmtTokens(report.totalTokens)} tokens)`),
	);
	lines.push(fg("muted", "─".repeat(104)));

	if (report.sessions.length === 0) {
		lines.push("");
		lines.push(fg("muted", "  No sessions with activity on this day."));
	} else {
		lines.push(
			fg("dim", `  ${padRight("Time", 19)}${padRight("Project", 20)}${padLeft("#", 4)}  ${padLeft("Tokens", 7)}  First message`),
		);
		for (const s of report.sessions) {
			const time = s.resumed ? fmtRangeTable(s) : `${fmtRangeTable(s)} (${fmtDur(s.startedAt, s.endedAt)})`;
			const first = s.userPrompts.length > 0 ? s.userPrompts[0] : "(no prompts)";
			lines.push(
				`  ${fg("text", padRight(time, 19))}${fg("accent", padRight(s.projectShort, 20))}${fg("text", padLeft(String(s.userPrompts.length), 4))}  ${fg("muted", padLeft(fmtTokens(s.tokens), 7))}  ${fg("muted", truncate(first, 46))}`,
			);
		}
	}

	lines.push(fg("muted", "─".repeat(104)));
	const footer: string[] = [];
	if (report.sessions.length > 0) {
		footer.push(`${localTime(report.rangeStart)} → ${localTime(report.rangeEnd)}`);
		footer.push(`${report.totalFiles} files changed`);
		const resumed = report.sessions.filter((s) => s.resumed).length;
		if (resumed > 0) footer.push(`* = resumed (${resumed})`);
	}
	footer.push("/report export for markdown");
	lines.push(fg("dim", `  ${footer.join("  ·  ")}`));

	const text = new Text(lines.join("\n"), 1, 1);
	const box = new Box(1, 1, (t) => theme.bg("customMessageBg", t));
	box.addChild(text);
	return box;
}

// ---------------------------------------------------------------------------
// Render: markdown (non-TUI chat + export)
// ---------------------------------------------------------------------------

function renderMarkdown(report: DayReport, summary?: string): string {
	const home = process.env.HOME || "";
	const out: string[] = [];
	out.push(`## Day report — ${englishDate(report.date)}`);
	out.push("");
	out.push(`*${report.sessions.length} sessions · ${report.totalPrompts} prompts · ~${fmtTokens(report.totalTokens)} tokens · ${report.totalFiles} files changed*`);
	out.push("");
	if (report.sessions.length === 0) {
		out.push("No sessions with activity on this day.");
		return out.join("\n");
	}
	out.push("| Time | Project | Prompts | Tokens | First message |");
	out.push("|---|---|---|---|---|");
	for (const s of report.sessions) {
		const time = s.resumed ? fmtRangeMd(s) : fmtRangeDur(s);
		const first = s.userPrompts.length > 0 ? truncate(s.userPrompts[0], 100).replace(/\|/g, "\\|") : "—";
		out.push(`| ${time} | ${s.projectShort} | ${s.userPrompts.length} | ${fmtTokens(s.tokens)} | ${first} |`);
	}
	if (report.sessions.some((s) => s.resumed)) {
		out.push("");
		out.push("*\\* = session resumed from a previous day*");
	}
	out.push("");
	out.push("### Session details");
	for (const s of report.sessions) {
		out.push("");
		const range = s.resumed ? `${fmtRangeMd(s)} (resumed)` : `${fmtRangeMd(s)} (${fmtDur(s.startedAt, s.endedAt)})`;
		out.push(`#### ${range} — ${s.projectShort} (${s.userPrompts.length} prompt${s.userPrompts.length === 1 ? "" : "s"})`);
		if (s.userPrompts.length > 0) {
			out.push(`- **first:** ${truncate(s.userPrompts[0], 300)}`);
			if (s.userPrompts.length > 1) {
				out.push(`- **last:** ${truncate(s.userPrompts[s.userPrompts.length - 1], 300)}`);
			}
		}
		if (s.filesTouched.length > 0) {
			out.push(`- **files (${s.filesTouched.length}):** ${s.filesTouched.slice(0, 12).map((f) => `\`${shortPath(f, home)}\``).join(", ")}${s.filesTouched.length > 12 ? " …" : ""}`);
		}
		if (s.errors > 0) out.push(`- **tool errors:** ${s.errors}`);
	}
	if (summary) {
		out.push("");
		out.push("---");
		out.push("");
		out.push(summary);
	}
	out.push("");
	return out.join("\n");
}

// ---------------------------------------------------------------------------
// AI summary
// ---------------------------------------------------------------------------

const SUMMARY_SYSTEM = "You are an assistant writing end-of-day reports for a software developer. Always reply in English, concrete and concise.";

function summaryPrompt(digest: string, dateLabel: string): string {
	return `Below is the digest of the AI agent work sessions of ${dateLabel} (one section per session: time and duration, project, user prompts, last assistant message, files changed).

Write a report with EXACTLY these sections (use exactly these headings):

## Done
Bulleted list: what was completed today. One line per result, with the project in parentheses when useful.

## Not finished / to continue
Bulleted list: what is left pending, with the suggested next step. Purely exploratory sessions or questions with no expected follow-up can be ignored.

## Notes (only if needed, otherwise omit the section)
Recurring errors, blockers, things to check tomorrow.

Rules:
- Be concrete and brief: no filler sentences, no intro paragraph.
- Do not invent anything: base everything on the digest only.
- If you cannot tell whether something is finished, put it under "Not finished" with a question mark.

<DIGEST>
${digest}
</DIGEST>`;
}

function assistantText(message: { content: unknown }): string {
	const c = message.content;
	if (!Array.isArray(c)) return "";
	return c
		.filter((p): p is { type: "text"; text: string } => !!p && (p as { type?: unknown }).type === "text")
		.map((p) => p.text)
		.join("\n")
		.trim();
}

async function generateSummary(
	ctx: ExtensionCommandContext,
	digest: string,
	dateLabel: string,
): Promise<string | null> {
	const model = ctx.model;
	if (!model) return null;
	const messages: Message[] = [
		{ role: "user", content: [{ type: "text", text: summaryPrompt(digest, dateLabel) }], timestamp: Date.now() },
	];
	const controller = new AbortController();
	const timer = setTimeout(() => controller.abort(), SUMMARY_TIMEOUT_MS);
	try {
		const stream = ctx.modelRegistry.streamSimple(
			model,
			{ systemPrompt: SUMMARY_SYSTEM, messages },
			{ signal: controller.signal, toolChoice: "none" },
		);
		// Consume the stream (without showing partials) and take the result.
		for await (const _event of stream) {
			/* single-shot: the report arrives all at once at the end */
		}
		const result = await stream.result();
		const text = assistantText(result);
		return text || null;
	} catch {
		return null;
	} finally {
		clearTimeout(timer);
	}
}

// ---------------------------------------------------------------------------
// Arguments
// ---------------------------------------------------------------------------

function parseDateToken(token: string): string | null {
	const t = token.toLowerCase();
	const today = localDateKey(new Date());
	if (t === "today") return today;
	if (t === "yesterday") return addDays(today, -1);
	if (/^\d{4}-\d{2}-\d{2}$/.test(t) && !Number.isNaN(new Date(`${t}T12:00:00`).getTime())) return t;
	return null;
}

const USAGE = "/report [today|yesterday|YYYY-MM-DD] [fast] · /report export [date] [file] · /daily is an alias";

async function handleReport(pi: ExtensionAPI, args: string, ctx: ExtensionCommandContext): Promise<void> {
	const tokens = (args ?? "").trim().split(/\s+/).filter(Boolean);
	const notify = (message: string, type: "info" | "warning" | "error" = "info") => {
		if (ctx.hasUI) ctx.ui.notify(message, type);
	};

	if (tokens.some((t) => t === "help" || t === "-h" || t === "--help")) {
		notify(USAGE, "info");
		return;
	}

	// --- export ---
	if (tokens[0]?.toLowerCase() === "export") {
		let date = localDateKey(new Date());
		let file = "";
		for (const t of tokens.slice(1)) {
			const d = parseDateToken(t);
			if (d) date = d;
			else if (!file) file = t;
		}
		const report = collectDay(date);
		const target = file ? path.resolve(ctx.cwd, file) : path.join(ctx.cwd, `report-${date}.md`);
		try {
			fs.writeFileSync(target, renderMarkdown(report), "utf8");
			notify(`Report saved to ${target} (${report.sessions.length} sessions)`, "info");
		} catch (error) {
			notify(`Export failed: ${String(error)}`, "error");
		}
		return;
	}

	// --- report ---
	let date = localDateKey(new Date());
	for (const t of tokens) {
		const d = parseDateToken(t);
		if (d) {
			date = d;
			break;
		}
	}
	const fast = tokens.some((t) => ["fast", "quick", "table", "table-only"].includes(t.toLowerCase()));

	const report = collectDay(date);
	if (report.sessions.length === 0) {
		notify(`No sessions with activity on ${date}.`, "warning");
		return;
	}

	// 1. Fast table (immediately).
	if (ctx.mode === "tui") {
		pi.appendEntry("daily-report-table", report);
	} else {
		// Outside the TUI (e.g. pi -p) there is no session or panel: print to stdout.
		process.stdout.write(renderMarkdown(report) + "\n");
		try {
			await pi.sendMessage(
				{ customType: "daily-report-table", content: renderMarkdown(report), display: true },
				{ triggerTurn: false },
			);
		} catch {
			/* no active session in this mode */
		}
	}

	// 2. AI summary (a single call, no tools).
	if (fast) {
		notify(`Table for ${date}: ${report.sessions.length} sessions, ${report.totalPrompts} prompts.`, "info");
		return;
	}
	if (!ctx.model) {
		notify("No model selected: showing the table only.", "warning");
		return;
	}
	notify("Generating the day summary…", "info");
	const summary = await generateSummary(ctx, buildDigest(report), englishDate(report.date));
	if (!summary) {
		notify("Summary failed (timeout or API error): keeping the table.", "warning");
		return;
	}
	if (ctx.mode !== "tui") {
		process.stdout.write(summary + "\n");
	}
	try {
		await pi.sendMessage(
			{ customType: "daily-report-summary", content: summary, display: true },
			{ triggerTurn: false },
		);
	} catch {
		/* no active session in this mode */
	}
}

// ---------------------------------------------------------------------------
// Extension
// ---------------------------------------------------------------------------

export default function (pi: ExtensionAPI) {
	pi.registerEntryRenderer("daily-report-table", (entry, _options, theme) => {
		try {
			const data = entry.data as DayReport | undefined;
			if (!data || !Array.isArray(data.sessions)) return undefined;
			return renderTablePanel(data, theme);
		} catch {
			return undefined;
		}
	});

	const completions = (prefix: string) => {
		const options = ["today", "yesterday", "fast", "export", "help"];
		const matches = options.filter((o) => o.startsWith(prefix.toLowerCase()));
		return matches.length > 0 ? matches.map((value) => ({ value, label: value })) : null;
	};

	for (const name of ["report", "daily"]) {
		pi.registerCommand(name, {
			description: "Day report: session table + done/not-finished summary",
			getArgumentCompletions: completions,
			handler: async (args, ctx) => {
				await handleReport(pi, args, ctx);
			},
		});
	}
}
